# Generated by Django 4.1.7 on 2023-03-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Albums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name="Artists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=40)),
                ("lastName", models.CharField(max_length=20)),
                ("company", models.CharField(max_length=80, null=True)),
                ("address", models.CharField(max_length=70, null=True)),
                ("city", models.CharField(max_length=40, null=True)),
                ("state", models.CharField(max_length=40, null=True)),
                ("country", models.CharField(max_length=40, null=True)),
                ("postalCode", models.CharField(max_length=10, null=True)),
                ("phone", models.CharField(max_length=24, null=True)),
                ("fax", models.CharField(max_length=24, null=True)),
                ("email", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="MediaTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="Tracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("composer", models.CharField(max_length=220, null=True)),
                ("milliseconds", models.IntegerField()),
                ("bytes", models.IntegerField()),
                ("unitPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.albums"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.genres"
                    ),
                ),
                (
                    "mediaType",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.mediatypes"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billingAddress", models.CharField(max_length=70, null=True)),
                ("billingCity", models.CharField(max_length=40, null=True)),
                ("billingCountry", models.CharField(max_length=40, null=True)),
                ("billingPostalCode", models.CharField(max_length=10, null=True)),
                ("billingState", models.CharField(max_length=40, null=True)),
                ("invoiceDate", models.DateTimeField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customers"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unitPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.invoices"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tracks"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lastName", models.CharField(max_length=20)),
                ("firstName", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=30)),
                ("birthDate", models.DateTimeField()),
                ("hireDate", models.DateTimeField()),
                ("address", models.CharField(max_length=70)),
                ("city", models.CharField(max_length=40)),
                ("state", models.CharField(max_length=40)),
                ("country", models.CharField(max_length=40)),
                ("postalCode", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=24)),
                ("fax", models.CharField(max_length=24)),
                ("email", models.CharField(max_length=60)),
                (
                    "reportsTo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.employees",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customers",
            name="supportRep",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.employees",
            ),
        ),
        migrations.AddField(
            model_name="albums",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.artists"
            ),
        ),
        migrations.CreateModel(
            name="PlaylistTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.playlists"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tracks"
                    ),
                ),
            ],
            options={
                "unique_together": {("playlist", "track")},
            },
        ),
    ]
